import { join } from "node:path";
import type { Config, GeneratedOutput, ParsedRule } from "../types/index.js";
import { loadIgnorePatterns } from "../utils/ignore.js";

export async function generateCopilotConfig(
  rules: ParsedRule[],
  config: Config,
  baseDir?: string
): Promise<GeneratedOutput[]> {
  const outputs: GeneratedOutput[] = [];

  // Generate individual instruction files for all rules
  for (const rule of rules) {
    const content = generateCopilotMarkdown(rule);
    const baseFilename = rule.filename.replace(/\.md$/, "");
    const outputDir = baseDir
      ? join(baseDir, config.outputPaths.copilot)
      : config.outputPaths.copilot;
    const filepath = join(outputDir, `${baseFilename}.instructions.md`);

    outputs.push({
      tool: "copilot",
      filepath,
      content,
    });
  }

  // Generate .copilotignore if .rulesyncignore exists
  // Note: This is unofficial support for community tools
  const ignorePatterns = await loadIgnorePatterns(baseDir);
  if (ignorePatterns.patterns.length > 0) {
    const copilotIgnorePath = baseDir 
      ? join(baseDir, ".copilotignore")
      : ".copilotignore";
    
    const copilotIgnoreContent = generateCopilotIgnore(ignorePatterns.patterns);
    
    outputs.push({
      tool: "copilot",
      filepath: copilotIgnorePath,
      content: copilotIgnoreContent,
    });
  }

  return outputs;
}

function generateCopilotMarkdown(rule: ParsedRule): string {
  const lines: string[] = [];

  // Add Front Matter for GitHub Copilot
  lines.push("---");
  lines.push(`description: "${rule.frontmatter.description}"`);
  if (rule.frontmatter.globs.length > 0) {
    lines.push(`applyTo: "${rule.frontmatter.globs.join(", ")}"`);
  } else {
    lines.push('applyTo: "**"');
  }
  lines.push("---");

  lines.push(rule.content);

  return lines.join("\n");
}

function generateCopilotIgnore(patterns: string[]): string {
  const lines: string[] = [
    "# Generated by rulesync from .rulesyncignore",
    "# This file is automatically generated. Do not edit manually.",
    "# Note: .copilotignore is not officially supported by GitHub Copilot.",
    "# This file is for use with community tools like copilotignore-vscode extension.",
    "",
    ...patterns
  ];
  
  return lines.join("\n");
}
