import { join } from "node:path";
import type { Config, GeneratedOutput, ParsedRule } from "../../types/index.js";
import { loadIgnorePatterns } from "../../utils/ignore.js";

export async function generateClineConfig(
  rules: ParsedRule[],
  config: Config,
  baseDir?: string
): Promise<GeneratedOutput[]> {
  const outputs: GeneratedOutput[] = [];

  // Generate rule files
  for (const rule of rules) {
    const content = generateClineMarkdown(rule);
    const outputDir = baseDir ? join(baseDir, config.outputPaths.cline) : config.outputPaths.cline;
    const filepath = join(outputDir, `${rule.filename}.md`);

    outputs.push({
      tool: "cline",
      filepath,
      content,
    });
  }

  // Generate .clineignore if .rulesyncignore exists
  const ignorePatterns = await loadIgnorePatterns(baseDir);
  if (ignorePatterns.patterns.length > 0) {
    const clineIgnorePath = baseDir ? join(baseDir, ".clineignore") : ".clineignore";

    const clineIgnoreContent = generateClineIgnore(ignorePatterns.patterns);

    outputs.push({
      tool: "cline",
      filepath: clineIgnorePath,
      content: clineIgnoreContent,
    });
  }

  return outputs;
}

function generateClineMarkdown(rule: ParsedRule): string {
  return rule.content.trim();
}

function generateClineIgnore(patterns: string[]): string {
  const lines: string[] = [
    "# Generated by rulesync from .rulesyncignore",
    "# This file is automatically generated. Do not edit manually.",
    "",
    ...patterns,
  ];

  return lines.join("\n");
}
