import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const gitignoreCommand = async (): Promise<void> => {
  const gitignorePath = join(process.cwd(), ".gitignore");

  const rulesFilesToIgnore = [
    "# Generated by rulesync - AI tool configuration files",
    "**/.github/copilot-instructions.md",
    "**/.github/instructions/",
    "**/.cursor/rules/",
    "**/.cursorignore",
    "**/.clinerules/",
    "**/.clineignore",
    "**/CLAUDE.md",
    "**/.claude/memories/",
    "**/.roo/rules/",
    "**/.rooignore",
    "**/.copilotignore",
    "**/GEMINI.md",
    "**/.gemini/memories/",
    "**/.aiexclude",
    "**/.aiignore",
    "**/.kiro/steering/",
    "**/.augment/rules/",
    "**/.augment-guidelines",
    "**/.mcp.json",
    "!.rulesync/.mcp.json",
    "**/.cursor/mcp.json",
    "**/.cline/mcp.json",
    "**/.vscode/mcp.json",
    "**/.gemini/settings.json",
    "**/.roo/mcp.json",
  ];

  let gitignoreContent = "";

  if (existsSync(gitignorePath)) {
    gitignoreContent = readFileSync(gitignorePath, "utf-8");
  }

  const linesToAdd: string[] = [];

  for (const rule of rulesFilesToIgnore) {
    if (!gitignoreContent.includes(rule)) {
      linesToAdd.push(rule);
    }
  }

  if (linesToAdd.length === 0) {
    console.log("✅ .gitignore is already up to date");
    return;
  }

  const newContent = gitignoreContent
    ? `${gitignoreContent.trimEnd()}\n\n${linesToAdd.join("\n")}\n`
    : `${linesToAdd.join("\n")}\n`;

  writeFileSync(gitignorePath, newContent);

  console.log(`✅ Added ${linesToAdd.length} rules to .gitignore:`);
  for (const line of linesToAdd) {
    if (!line.startsWith("#")) {
      console.log(`  ${line}`);
    }
  }
};
